stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache curl
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region us-west-2

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u AWS -p $(aws ecr get-login-password --region us-west-2) $ECR_REGISTRY
    - docker build -t $ECR_REPOSITORY:latest .
    - docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST 'aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $ECR_REGISTRY && docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest && docker-compose up -d'
