version: '3'
services:
  web:
    image: 767397966663.dkr.ecr.eu-north-1.amazonaws.com/app_py:latest
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASS=password
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
