name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        # Add your Docker build commands here
        # For example: docker build -t your_image_name .

  deploy_to_ec2:
    needs: build_docker_image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        apk add --no-cache openssh
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

    - name: Download yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq

    - name: Deploy to EC2
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        AWS_REGION: eu-north-1
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$EC2_HOST "
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY &&
        cd App_Py &&
        yq e '.services.web.image = \"$ECR_REGISTRY/$ECR_REPOSITORY:latest\"' -i docker-compose.yml &&
        docker-compose down &&
        docker-compose up -d"
